### ISSUE TITLE
Old link to MLJScientificTypes instead of ScientificTypes

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/DataScienceTutorials.jl#1]
In this tutorial:

https://juliaai.github.io/DataScienceTutorials.jl/data/scitype/

**Comment by tlienart** [comment]
I'm on it

done in https://github.com/JuliaAI/DataScienceTutorials.jl/commit/2a1b024ddf411bbc5b9ac259dcc26a66a16c069c

**Comment by ablaom** [comment]
Thanks ❤️
