### ISSUE TITLE
Some typo or formatting issue on the landing page?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/DataScienceTutorials.jl#109]
Bullet point 2 looks a bit odd:

<img width="665" alt="Screen Shot 2020-07-13 at 4 33 47 PM" src="https://user-images.githubusercontent.com/30517088/87271245-c99a8e80-c526-11ea-9fe5-0c02f5a72dff.png">

**Comment by gd1989** [comment]
@ablaom I'll take care of that
