### ISSUE TITLE
404 error clicking on "Data Processing" on homepage sidebar

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/DataScienceTutorials.jl#126]
https://alan-turing-institute.github.io/DataScienceTutorials.jl/data/processing/

**Comment by tlienart** [comment]
Yes we’re aware of it cc @gd1989 

We went through quite some pain to fix issues and deploy the site and geoff managed in the end at the cost of putting aside a few things which we still have to fix

**Comment by gd1989** [comment]
ok, it's live now
