### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/DataScienceTutorials.jl#150]
Today a user noticed that https://alan-turing-institute.github.io/DataScienceTutorials.jl/ is down. I am experiencing the same thing. 

@tlienart @giordano

**Comment by tlienart** [comment]
I force pushed it back to where it was before (187348b44a199cc901f2b69142bf16ddc14e8f47) 

My plan is to sort this repo out by the end of May but there will likely be some bumps.

**Comment by quazi-irfan** [comment]
Hello, the website was back to normal for a while, but now it's reporting 404 again.

**Comment by tlienart** [comment]
Thanks @quazi-irfan , I force pushed again, and checked out the branch on a safe branch that will not get updated.

**Comment by quazi-irfan** [comment]
Thanks! It's back to normal again.

**Comment by tlienart** [comment]
@quazi-irfan take note of #152 so some of the tutorials might be outdated though we're working on that.

**Comment by quazi-irfan** [comment]
Thanks for the heads up. Is there any particular section that more outdated than others? My goal is to go over the entire documentation to try to familiarize myself with MLJ and MLJ tuning.

I was wondering if you would like me to send some small fixed as pull request. For example, I've seen some links that point to old documentations - those should be very small fixes.

**Comment by tlienart** [comment]
If you could open an issue with all your feedback for minor fixes like this, it would be much appreciated, things like links etc would definitely be very useful.

In terms of changes, there are no huge differences, and you can always check the corresponding `.jl` file on the master branch which does contain the latest fixes (it's just not matched to the site right now).
