### ISSUE TITLE
Calling learning network machine `mach` (depr warning)

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/DataScienceTutorials.jl#155]
```
┌ Warning: Calling a learning network machine `mach` with no arguments, as in`mach()`, is deprecated and could lead to unexpected behaviour for `Composite` models with fields that are not models. Instead of `fit!(mach, verbosity=verbosity); return mach()` use `return!(mach, model, verbosity)`, where `model` is the `Model` instance appearing in your `MLJBase.fit` signature. Query the `return!` doc-string for details. 
```

This happens a bunch, e.g. in EX-AMES. Would be good to have someone aware of the recent changes have a look and tell me how things should be written now.

**Comment by ablaom** [comment]
Can you please point to the Manifest.toml giving rise to this problem? Cheers.

**Comment by tlienart** [comment]
https://github.com/alan-turing-institute/DataScienceTutorials.jl/tree/tl-update/_literate/EX-AMES has the Manifest and the script. 

Thanks Anthony

**Comment by ablaom** [comment]
I can't instantiate that manifest using Julia 1.6 or julia 1.5.

```julia
ERROR: AssertionError: sourcepath !== nothing
Stacktrace:
 [1] is_package_downloaded at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1670 [inlined]
```

cc @giordano

**Comment by giordano** [comment]
With what version was the manifest generated?  As a rule of a thumb, a manifest generated with Julia v1.X may not be instantiated with Julia v1.Y, with Y < X (but really, _strictly speaking_ a manifest makes sense _only_ for the version of Julia it was generated with).  As a result, when one gives you a manifest they should _always_ tell you what version of Julia it was generated with.

**Comment by tlienart** [comment]
Generated with 1.7

But I don't think this matters for the reported warnings. If you check the version of MLJ and MLJBase, it's the latest ones as far as I can tell.

So if you just activate the project and run the script on 1.6 ignoring the manifest do you not get any warnings?
