### ISSUE TITLE
[Suggestion] Add link on every page to DataScienceTutorials.jl issues to assist in getting feedback and errata

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/DataScienceTutorials.jl#2]

**Comment by tlienart** [comment]
you mean have one issue per DST page and link to it from the page so that people can ask questions?

(PS: note that this repo is archived in favour of the JuliaAI one)

**Comment by ablaom** [comment]
Not really to ask questions, more to point out problems. I was just thinking of a link that appears on the top of every page like this one:

Please report problems with tutorials [here](https://github.com/JuliaAI/DataScienceTutorials.jl/issues/new). 

I'm open to suggestions for something fancier, but we probably have higher priorities just now 😄 .

**Comment by tlienart** [comment]
ok so what you're suggesting is very easy, I'll add it now.

Done.
