### ISSUE TITLE
no need to add formatting to output of schema any more?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/DataScienceTutorials.jl#50]

**Comment by tlienart** [comment]
could you clarify what you mean here? I self-assigned but I don't remember what this is about :octocat:

**Comment by ablaom** [comment]
For example on this page https://alan-turing-institute.github.io/MLJTutorials/end-to-end/wine/ you have 

```julia
sch = schema(X)
println(rpad(" Name", 28), "| Scitype")
println("-"^45)
for (name, scitype) in zip(sch.names, sch.scitypes)
    println(rpad("$name", 30), scitype)
end
```

Just the first line suffices, most likely.
