### ISSUE TITLE
Tutorial instructions

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/DataScienceTutorials.jl#74]
Many users might be new to Julia, programming, ML etc. 
They may not understand the point having an identical environment. 
It might help to "hold their hand" a bit more & be more specific, eg they may not know how to `cd`. 

One option: add a few details to current instructions  
1. Create a folder 
Go to desired directory: `cd("/Users/AZevelev/Dropbox/")`
Create folder: `mkdir("MLJ_tutorial")`
2. Download this Project.toml and this Manifest.toml and save in that same folder
3. Get the relevant versions of the packages.
`julia> using Pkg; Pkg.activate("."); Pkg.instantiate();`

Another option: instantiate from url (get started immediately, no need to download `.toml`)
https://github.com/QuantEcon/InstantiateFromURL.jl

**Comment by tlienart** [comment]
@gd1989  would you like to take this on?

Many thanks @azev77 !!

**Comment by gd1989** [comment]
Yes, I am on it. Thanks!

**Comment by tlienart** [comment]
@gd1989 for the instantiation from URL which is great, I’ll have a crack at it later so don’t worry about it for now :)

**Comment by tlienart** [comment]
I'll close this and open a specific one for the instantiate from URL
