### ISSUE TITLE
Additional lab from quant econ

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/DataScienceTutorials.jl#76]
From @drcxcruz :

> should I create a new github pull request for the other lab:
https://notes.quantecon.org/submission/5e653f616479ca001038be0f  ?  or you
can grab it from the notes site?

cc' @gd1989 that could be a nice addition too :)

**Comment by drcxcruz** [comment]
Hello,

I created this lab all by myself :)   I have created a Pull Request in the
MLJ github.

Create Tutorial 3Models.ipynb by Cruz #78

Thank you!

**Comment by tlienart** [comment]
thanks a lot! we'll look into it :)
